### ISSUE TITLE
Error: Vector does not handle this message 

### ISSUE THREAD

**Issue by hyansuper** [anki/vector-python-sdk#28]
I test the following script on Ubuntu18.04 with Python version 3.6.8.
from the ios app I can see the Vector's firmware version is 1.3.0.2510
from pip3 freeze I can see the sdk version is uptodate "anki-vector==0.6.0"
```python
import anki_vector

def main():
    args = anki_vector.util.parse_command_args()
    with anki_vector.Robot() as robot:
        robot.say_text("Hello")
if __name__ == "__main__":
    main()

```

error:
```
11:07:01.558               robot.Robot WARNING  No serial number or name provided. Automatically selecting 0090416a
11:07:01.560     connection.Connection    INFO  Connecting to 192.168.0.100:443 for Vector-P4E1 using /home/hyan/.anki_vector/Vector-P4E1-0090416a.cert
11:07:02.058     connection.Connection    INFO  BehaviorControl control_granted_response { }
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/anki_vector/connection.py", line 749, in log_handler
    result = await func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/anki_vector/animation.py", line 191, in load_animation_trigger_list
    return await self._load_animation_trigger_list()
  File "/usr/local/lib/python3.6/dist-packages/anki_vector/animation.py", line 141, in _load_animation_trigger_list
    result = await self.grpc_interface.ListAnimationTriggers(req)
  File "/usr/local/lib/python3.6/dist-packages/aiogrpc/channel.py", line 40, in __call__
    return await fut
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method ListAnimationTriggers"
	debug_error_string = "{"created":"@1566616023.372967889","description":"Error received from peer ipv4:192.168.0.100:443","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"unknown method ListAnimationTriggers","grpc_status":12}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "say_text.py", line 8, in <module>
    main()
  File "say_text.py", line 5, in main
    with anki_vector.Robot() as robot:
  File "/usr/local/lib/python3.6/dist-packages/anki_vector/robot.py", line 742, in __enter__
    self.connect(self.behavior_activation_timeout)
  File "/usr/local/lib/python3.6/dist-packages/anki_vector/robot.py", line 666, in connect
    anim_trigger_request = self._anim.load_animation_trigger_list()
  File "/usr/local/lib/python3.6/dist-packages/anki_vector/connection.py", line 806, in result
    return future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/dist-packages/anki_vector/connection.py", line 751, in log_handler
    raise connection_error(rpc_error) from rpc_error
anki_vector.exceptions.VectorUnimplementedException: StatusCode.UNIMPLEMENTED: unknown method ListAnimationTriggers

Vector does not handle this message.
```

**Comment by hyansuper** [comment]
The above exception does not actually cause connection problem, I can get vector to say hello using python interactive mode:
```
>>> import anki_vector
>>> robot=anki_vector.Robot()
11:33:18.642               robot.Robot WARNING  No serial number or name provided. Automatically selecting 0090416a
>>> robot.__enter__()
... [the same exception from above comment] ...
>> robot.say_text("hello")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Robot' object has no attribute 'say_text'
>>> robot.behavior.say_text("hello")
[ now the robot says hello! ]
```

**Comment by hyansuper** [comment]
solved by reinstalling anki_vector, not knowing why
