### ISSUE TITLE
Can't configure Vector

### ISSUE THREAD

**Issue by lordlouckster** [anki/vector-python-sdk#40]
I'm trying to authenticate Vector with SDK, but when I type my serial number, I keep getting these errors:
```
socket.gaierror: [Errno 11001] getaddrinfo failed
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000226CF8D4F40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='session-certs.token.global.anki-services.com', port=443): Max retries exceeded with url: /vic/<serialnumber>(Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000226CF8D4F40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='session-certs.token.global.anki-services.com', port=443): Max retries exceeded with url: /vic/<serialnumber> (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000226CF8D4F40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

**Comment by lordlouckster** [comment]
I think session-certs.token.global.anki-services.com is down. Last time when I set Vector with SDK it worked fine.

**Comment by paguos** [comment]
I have the same problem 😞

**Comment by grant-olson** [comment]
We have a cloud engineer investigating now. Will report back soon.

**Comment by lordlouckster** [comment]
I asked about this in Anki's forum. They said to try this: 
Enter “ https://ota-cdn.anki.com/ok ” into a browser on the same WiFi network as Vector
If a file containing “OK” downloads, the Cloud is available and accessible from your device’s WiFi network
I tried it, and got ok file. Still can't configure Vector.

**Comment by grant-olson** [comment]
We've identified an issue where our domain registrar expired a particular
domain registration in error. We're working with them to correct the
situation. Once that happens things should work again and we'll let you
know here. But for now we're also waiting for the registrar to resolve the
issue.

**Comment by grant-olson** [comment]
Our registrar has fixed the problem and we can resolve the domain correctly here. Can you try again and let us know if it works for you now?

**Comment by paguos** [comment]
> Our registrar has fixed the problem and we can resolve the domain correctly here. Can you try again and let us know if it works for you now?

It works! Thanks for the quick fix 👍

**Comment by lordlouckster** [comment]
SUCCESS!

**Comment by tasarimcidayi** [comment]
> Our registrar has fixed the problem and we can resolve the domain correctly here. Can you try again and let us know if it works for you now?

**I get the following error and cannot complete the configure part, can you help? Thank you!**

`Downloading Vector certificate from Anki...Traceback (most recent call last):
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Program Files\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    conn.connect()
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001F88C8402E0>: Failed to resolve 'session-certs.token.global.anki-services.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='session-certs.token.global.anki-services.com', port=443): Max retries exceeded with url: /vic/00308c45 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F88C8402E0>: Failed to resolve 'session-certs.token.global.anki-services.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\anki_vector\configure\__main__.py", line 322, in <module>
    main(Api())
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\anki_vector\configure\__main__.py", line 302, in main
    cert, serial = get_cert(args.serial)
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\anki_vector\configure\__main__.py", line 101, in get_cert
    r = requests.get('https://session-certs.token.global.anki-services.com/vic/{}'.format(serial))
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='session-certs.token.global.anki-services.com', port=443): Max retries exceeded with url: /vic/00308c45 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F88C8402E0>: Failed to resolve 'session-certs.token.global.anki-services.com' ([Errno 11001] getaddrinfo failed)"))
`

**Comment by MohamedNagyMostafa** [comment]
i am facing the same issue now!!
