### ISSUE TITLE
Vector 2.0 06_face_image example causes Error 914

### ISSUE THREAD

**Issue by Cole1220** [anki/vector-python-sdk#55]
I run the SDK example 06_face_image and get Error 914 (NO_ENGINE_PROCESS | Vic-engine stopped unexpectedly.) (https://support.digitaldreamlabs.com/article/96-vector-status-codes). Clean fork, examples 1-5 seem to work just fine so far

Output:

PS C:\Users\Robin\Documents\GitHub\vector-python-sdk> & C:/Users/Robin/AppData/Local/Microsoft/WindowsApps/python3.9.exe c:/Users/Robin/Documents/GitHub/vector-python-sdk/examples/tutorials/06_face_image.py
17:22:52.091     connection.Connection    INFO  BehaviorControl control_granted_response { }
17:22:52.558       events.EventHandler WARNING  Unknown Event type
17:22:52.559       events.EventHandler WARNING  Unknown Event type
17:22:52.566       events.EventHandler WARNING  Unknown Event type
17:22:52.983       events.EventHandler WARNING  Unknown Event type
17:22:53.381       events.EventHandler WARNING  Unknown Event type
17:22:53.805       events.EventHandler WARNING  Unknown Event type
Display image on Vector's face...
17:22:54.166       events.EventHandler WARNING  Unknown Event type
__anext__ grpc exception
Traceback (most recent call last):
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiogrpc\utils.py", line 145, in cb
    fut.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiogrpc\utils.py", line 131, in _next
    return next(self._iterator)
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_channel.py", line 475, in __next__
    return self._next()
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_channel.py", line 881, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "End of TCP stream"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:192.168.0.20:443 {created_time:"2023-04-05T21:22:56.416310418+00:00", grpc_status:14, grpc_message:"End of TCP stream"}"
>
__anext__ grpc exception
Traceback (most recent call last):
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiogrpc\utils.py", line 145, in cb
    fut.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiogrpc\utils.py", line 131, in _next
    return next(self._iterator)
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_channel.py", line 475, in __next__
    return self._next()
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\grpc\_channel.py", line 881, in _next
    raise self
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "End of TCP stream"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:192.168.0.20:443 {created_time:"2023-04-05T21:22:56.416748527+00:00", grpc_status:14, grpc_message:"End of TCP stream"}"
>
Traceback (most recent call last):
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\anki_vector\connection.py", line 749, in log_handler
    result = await func(*args, **kwargs)
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\anki_vector\world.py", line 466, in delete_custom_objects
    last_blocking_call = await self.grpc_interface.DeleteCustomObjects(req)
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\aiogrpc\channel.py", line 40, in __call__
    return await fut
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.168.0.20:443: WSA Error"
        debug_error_string = "UNKNOWN:failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.168.0.20:443: WSA Error {grpc_status:14, created_time:"2023-04-05T21:23:00.718482033+00:00"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\Robin\Documents\GitHub\vector-python-sdk\examples\tutorials\06_face_image.py", line 57, in <module>
    main()
  File "c:\Users\Robin\Documents\GitHub\vector-python-sdk\examples\tutorials\06_face_image.py", line 53, in main
    time.sleep(duration_s)
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\anki_vector\robot.py", line 746, in __exit__
    self.disconnect()
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\anki_vector\robot.py", line 733, in disconnect
    self.world.close()
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\anki_vector\world.py", line 285, in close
    self.delete_custom_objects()
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\anki_vector\connection.py", line 806, in result
    return future.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Robin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\anki_vector\connection.py", line 751, in log_handler
    raise connection_error(rpc_error) from rpc_error
anki_vector.exceptions.VectorUnavailableException: StatusCode.UNAVAILABLE: failed to connect to all addresses; last error: UNAVAILABLE: ipv4:192.168.0.20:443: WSA Error

Unable to reach Vector.

**Comment by wimdecorte** [comment]
Same issue.
Emailed support at DDL and they don't seem to support their own SDK and its examples.
