### ISSUE TITLE
message took too long to complete

### ISSUE THREAD

**Issue by cfreidsy** [anki/vector-python-sdk#56]
Every tutorial I try running produces the following:

C:\Users\reidsy\Documents\vector-python-sdk-master\vector-python-sdk-master\examples\tutorials>py 01_hello_world.py
21:18:53.926               robot.Robot WARNING  No serial number or name provided. Automatically selecting 00803473
21:18:53.942     connection.Connection    INFO  Connecting to [192.168.1.18:443](http://192.168.1.18:443/) for Vector-C7T5 using C:\Users\reidsy\.anki_vector\Vector-C7T5-00803473.cert
21:19:00.261     connection.Connection    INFO  BehaviorControl control_granted_response { }
Traceback (most recent call last):
  File "C:\Users\reidsy\AppData\Roaming\Python\Python36\site-packages\anki_vector\connection.py", line 749, in log_handler
    result = await func(*args, **kwargs)
  File "C:\Users\reidsy\AppData\Roaming\Python\Python36\site-packages\anki_vector\animation.py", line 168, in load_animation_list
    return await self._load_animation_list()
  File "C:\Users\reidsy\AppData\Roaming\Python\Python36\site-packages\anki_vector\animation.py", line 134, in _load_animation_list
    result = await self.grpc_interface.ListAnimations(req)
  File "C:\Users\reidsy\AppData\Roaming\Python\Python36\site-packages\aiogrpc\channel.py", line 40, in __call__
    return await fut
grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
        status = StatusCode.DEADLINE_EXCEEDED
        details = "ListAnimations request timed out"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:[192.168.1.18:443](http://192.168.1.18:443/) {grpc_message:"ListAnimations request timed out", grpc_status:4, created_time:"2023-04-07T01:19:05.664456406+00:00"}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "01_hello_world.py", line 33, in <module>
    main()
  File "01_hello_world.py", line 27, in main
    with anki_vector.Robot(args.serial) as robot:
  File "C:\Users\reidsy\AppData\Roaming\Python\Python36\site-packages\anki_vector\robot.py", line 742, in __enter__
    self.connect(self.behavior_activation_timeout)
  File "C:\Users\reidsy\AppData\Roaming\Python\Python36\site-packages\anki_vector\robot.py", line 663, in connect
    anim_request = self._anim.load_animation_list()
  File "C:\Users\reidsy\AppData\Roaming\Python\Python36\site-packages\anki_vector\connection.py", line 806, in result
    return future.result()
  File "C:\Users\reidsy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\_base.py", line 405, in result
    return self.__get_result()
  File "C:\Users\reidsy\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "C:\Users\reidsy\AppData\Roaming\Python\Python36\site-packages\anki_vector\connection.py", line 751, in log_handler
    raise connection_error(rpc_error) from rpc_error
anki_vector.exceptions.VectorTimeoutException: StatusCode.DEADLINE_EXCEEDED: ListAnimations request timed out

Message took too long to complete.

**Comment by pepedocs** [comment]
Vector probably took long to respond hence the timeout. Why it took long to respond? I don't know. But I get this regularly when Vector is idle for example and I try to interact with it.

**Comment by cfreidsy** [comment]
I found the issue. It was an antivirus issue.

**Comment by GruntingRhino** [comment]
This happens to me a lot, but I usually just keep on running the program and it works every 3-4 tries.
