### ISSUE TITLE
Can't Configure Vector

### ISSUE THREAD

**Issue by tasarimcidayi** [anki/vector-python-sdk#57]
I get the following error and cannot complete the configure part, can you help? Thank you!

```
Downloading Vector certificate from Anki...Traceback (most recent call last):
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 203, in _new_conn
sock = connection.create_connection(
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\util\connection.py", line 60, in create_connection
for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
File "C:\Program Files\Python39\lib\socket.py", line 953, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 790, in urlopen
response = self._make_request(
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 491, in _make_request
raise new_e
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 467, in _make_request
self._validate_conn(conn)
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
conn.connect()
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 611, in connect
self.sock = sock = self._new_conn()
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\connection.py", line 210, in _new_conn
raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001F88C8402E0>: Failed to resolve 'session-certs.token.global.anki-services.com' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 486, in send
resp = conn.urlopen(
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\connectionpool.py", line 844, in urlopen
retries = retries.increment(
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\urllib3\util\retry.py", line 515, in increment
raise MaxRetryError(_pool, url, reason) from reason # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='session-certs.token.global.anki-services.com', port=443): Max retries exceeded with url: /vic/00308c45 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F88C8402E0>: Failed to resolve 'session-certs.token.global.anki-services.com' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Program Files\Python39\lib\runpy.py", line 197, in run_module_as_main
return run_code(code, main_globals, None,
File "C:\Program Files\Python39\lib\runpy.py", line 87, in run_code
exec(code, run_globals)
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\anki_vector\configure_main.py", line 322, in
main(Api())
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\anki_vector\configure_main.py", line 302, in main
cert, serial = get_cert(args.serial)
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\anki_vector\configure_main.py", line 101, in get_cert
r = requests.get('[https://session-certs.token.global.anki-services.com/vic/{}'.format(serial)](https://session-certs.token.global.anki-services.com/vic/%7B%7D'.format(serial)))
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\requests\api.py", line 73, in get
return request("get", url, params=params, **kwargs)
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\requests\api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 589, in request
resp = self.send(prep, **send_kwargs)
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\requests\sessions.py", line 703, in send
r = adapter.send(request, **kwargs)
File "C:\Users\Burak\AppData\Roaming\Python\Python39\site-packages\requests\adapters.py", line 519, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='session-certs.token.global.anki-services.com', port=443): Max retries exceeded with url: /vic/00308c45 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001F88C8402E0>: Failed to resolve 'session-certs.token.global.anki-services.com' ([Errno 11001] getaddrinfo failed)"))
```

**Comment by MohamedNagyMostafa** [comment]
I am facing the same issue

**Comment by shalodey** [comment]
I believe this is due to DDL shutting down Vector servers. It attempts to access the servers, however fails.

**Comment by UOFMGUY** [comment]
Thank you for the reply.But not sure I completely understand.Is it:1) the servers are shut down at certain times? If so is there a schedule.2) The servers are down permanently?Can you clarify what you mean by "DDL shutting down Vector servers."Thanks,JohnPlease excuse any mistakes, this was sent from my mobile phone.On May 30, 2024, at 9:37 AM, shalodey ***@***.***> wrote:﻿
I believe this is due to DDL shutting down Vector servers. It attempts to access the servers, however fails.

**Comment by Rj2537** [comment]
To all of you,

Ddl being a shit of a company has shut  down the servers, hence I would recommend you installing wire-pod at https://github.com/kercre123/wire-pod

**Comment by Rj2537** [comment]
> Thank you for the reply.But not sure I completely understand.Is it:1) the servers are shut down at certain times? If so is there a schedule.2) The servers are down permanently?Can you clarify what you mean by "DDL shutting down Vector servers."Thanks,JohnPlease excuse any mistakes, this was sent from my mobile phone.On May 30, 2024, at 9:37 AM, shalodey ***@***.***> wrote:﻿
> I believe this is due to DDL shutting down Vector servers. It attempts to access the servers, however fails.
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

They shut down completely. In theory they said it will come back but I don't trust them
